---
name: ci
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v4.0.2
        with:
          path: ~/.poetry
          key: poetry
      - name: Setup Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: | 
          python -m venv ~/.poetry
          ~/.poetry/bin/pip --disable-pip-version-check install poetry
      - name: Add Poetry to $PATH
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"
          cache: poetry
      - run: poetry install
      - name: Run Tests
        run: poetry run python -m pytest --cov --cov-report=xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.0.0
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
